apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kuv2a5ol9-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/kuv2a5ol9-java-quarkus-gitops